---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingress-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpd-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - istio-ingress-gateway
  http:
    - match:
        - uri:
            prefix: /httpd
      route:
        - destination:
            host: httpd-service
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tomcat-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - istio-ingress-gateway
  http:
    - match:
        - uri:
            prefix: /tomcat
      route:
        - destination:
            host: tomcat-service.default.svc.cluster.local
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tomcat-destinationrule
spec:
  host: tomcat-service.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: JSESSIONID
          ttl: 0s
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpd-destinationrule
  namespace: default
spec:
  host: httpd-service.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: JSESSIONID
          ttl: 0s
