# Dockerfile for Apache HTTP Server
FROM httpd:2.4.64

# Install curl
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Copy custom configuration
COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf

# Expot port
EXPOSE 80