# Dockerfile for Tomcat
FROM tomcat:11.0.9-jdk17

# Install curl
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Add the application to the Tomcat webapps directory
COPY ./ROOT.war /usr/local/tomcat/webapps/

# Expose port 8080 for Tomcat
EXPOSE 8080

# Start both Tomcat
CMD ["sh", "-c", "/usr/local/tomcat/bin/catalina.sh run]