# Dockerfile for Tomcat with Filebeat
FROM tomcat:11.0.9-jdk17

# TODO: Add the application to the Tomcat webapps directory
#COPY ./simple-app.war /usr/local/tomcat/webapps/

# Install Filebeat
RUN apt-get update && apt-get install -y wget && \
    wget https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.17.0-amd64.deb && \
    dpkg -i filebeat-7.17.0-amd64.deb && \
    rm filebeat-7.17.0-amd64.deb

# TODO: Copy Filebeat configuraiton
#COPY ./filebeat.yml /etc/filebeat/filebeat.yml

# Expose port 8080 for Tomcat
EXPOSE 8080

# Start both Tomcat and Filebeat
CMD ["sh", "-c", "/usr/local/tomcat/bin/catalina.sh run & filebeat -e"]